//
// FlowsheetShowsIdForceEndPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FlowsheetShowsIdForceEndPostRequest: Sendable, Codable, Hashable {

    /** Override the derived end instant. Omit it and the show is closed at its last logged entry (floored at `start_time`), which is the right answer for the abandoned shows this endpoint exists to reach and is what the description above documents.  Supply it when an operator knows better than the flowsheet does — a show whose DJ stopped logging an hour before they actually went off the air, say. Bounded on both ends: it must be at or after the show's `start_time` and at or before now, or the request is a 400. The lower bound keeps a closed show from carrying an interval that cannot overlap its own airdate; the upper bound keeps a show from claiming to have ended in the future.  */
    public var endedAt: Date?

    public init(endedAt: Date? = nil) {
        self.endedAt = endedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endedAt = "ended_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(endedAt, forKey: .endedAt)
    }
}

