//
// OnAirDJ.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OnAirDJ: Sendable, Codable, Hashable {

    /** The DJ's better-auth `auth_user.id` (an opaque `varchar(255)` string), or `null` for a legacy/tubafrenzy-mirrored show whose on-air DJ has no Backend-Service account (their identity is `legacy_dj_name`, surfaced on `/flowsheet/djs-on-air` with a null id). Historically mistyped as `integer`; corrected to the nullable string it is at runtime (BS#1547). */
    public var id: String?
    /** The DJ's public on-air handle, never the DJ's legal name. For a DJ with a Backend-Service account, the DJ's chosen handle (`user.djName`); for a legacy/tubafrenzy-mirrored show with no account, the full PII-safe chain (BS#1371) down to `shows.legacy_dj_name`. */
    public var djName: String

    public init(id: String?, djName: String) {
        self.id = id
        self.djName = djName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case djName = "dj_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(djName, forKey: .djName)
    }
}

